mysite/apibook/urls.py
from django.urls import path

from apibook.views import (
    DeviceView,
    SearchDeviceView,
    FilterDeviceView,
)

app_name = 'apibook'

urlpatterns = [
    path('search', SearchDeviceView.as_view(), name='search'),
    path('filter', FilterDeviceView.as_view(), name='filter'),
    path('device', DeviceView.as_view(), name='device'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('refbook.urls')),
    path('apibook/v1/', include('apibook.urls')),
]

mysite/refbook/urls.py
from django.urls import path
from refbook.views import DevicesListView, CeateDeviceView

app_name = 'refbook'

urlpatterns = [
    path('', DevicesListView.as_view(), name='device_list'),
    path('refbook-create', CeateDeviceView.as_view(), name='create_device'),
]

mysite/apibook/models.py
from django.db import models

# Create your models here.

mysite/refbook/models.py
from django.db import models


class NotificationDevice(models.Model):

    TYPE_CHOICE = (
        (1, 'Сирена'),
        (2, 'Громкоговоритель'),
    )
    device_type = models.IntegerField(choices=TYPE_CHOICE)
    address = models.CharField(max_length=255)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    sound_cover_zone = models.IntegerField()

    class Meta:
        ordering = ['-id']
        verbose_name = 'Notification Device'
        verbose_name_plural = 'Notifications Devices'

    def __str__(self):
        return f'Девайс: {self.get_device_type_display()} Адресс: {self.address}'

mysite/refbook/forms.py
from django import forms

from refbook.models import NotificationDevice


class DeviceForm(forms.ModelForm):
    """
        Форма добавления устройства.
    """
    class Meta:
        model = NotificationDevice
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(DeviceForm, self).__init__(*args, **kwargs)
        self.fields['device_type'].label = "Тип девайса"
        self.fields['address'].label = "Адресс размещения"
        self.fields['latitude'].label = "Широта"
        self.fields['longitude'].label = "Долгота"
        self.fields['sound_cover_zone'].label = "Радиус зоны звукопокрытия"

mysite/apibook/views.py
from django.shortcuts import get_object_or_404

from rest_framework import permissions
from rest_framework import generics
from rest_framework import filters
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from django_filters import rest_framework as filter_rest

from refbook.models import NotificationDevice

from apibook.serializers import DeviceSerializer


class SearchDeviceView(generics.ListAPIView):
    """
    Поиск утсройств по адресу, широте и долготе.
    """
    permission_classes = (permissions.AllowAny,)
    filter_backends = (filters.SearchFilter,)
    search_fields = ('address', 'latitude', 'longitude')
    queryset = NotificationDevice.objects.all()
    serializer_class = DeviceSerializer


class FilterDeviceView(generics.ListAPIView):
    """
    Фильтрация устройств девайсов по типу, адресу, зоне звукового погрытия.
    """
    permission_classes = (permissions.AllowAny,)
    filter_backends = (filter_rest.DjangoFilterBackend,)
    filterset_fields = ('device_type', 'address', 'sound_cover_zone')
    queryset = NotificationDevice.objects.all()
    serializer_class = DeviceSerializer


class DeviceView(APIView):
    """
    Полный CRUD для устройств.
    """
    permission_classes = (permissions.AllowAny,)

    def get(self, request, *args, **kwargs):
        device = NotificationDevice.objects.all()
        serializer = DeviceSerializer(device, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = DeviceSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, *args, **kwargs):
        device = request.GET.get('device', None)
        if not device:
            return Response({'errors': 'No device provided'}, status=status.HTTP_400_BAD_REQUEST)
        try:
            item = get_object_or_404(NotificationDevice, pk=device)
        except (TypeError, ValueError):
            return Response({'errors': 'Argument must be int'}, status=status.HTTP_400_BAD_REQUEST)
        data = request.data
        serializer = DeviceSerializer(item, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, *args, **kwargs):
        device = request.GET.get('device', None)
        if not device:
            return Response({'errors': 'No device provided'}, status=status.HTTP_400_BAD_REQUEST)
        try:
            item = get_object_or_404(NotificationDevice, pk=device)
        except (TypeError, ValueError):
            return Response({'errors': 'Argument must be int'}, status=status.HTTP_400_BAD_REQUEST)
        item.delete()
        message = {
            'message': 'Device {type} with longitude: {longitude} and latitude {latitude} deleted successfully'.format(
                type=item.device_type,
                longitude=item.longitude,
                latitude=item.latitude,
            ),
        }
        return Response(message, status=status.HTTP_200_OK)

mysite/refbook/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect, JsonResponse

from refbook.forms import DeviceForm
from refbook.models import NotificationDevice


class DevicesListView(ListView):
    """
    Список всех устройств с пагинацией по 4.
    """
    model = NotificationDevice
    paginate_by = 4
    context_object_name = 'devices'
    template_name = 'refbook/list_devices.html'


class CeateDeviceView(CreateView):
    """
    Ajax валидация формы. Добавляет новое устройство в базу данных в случае успеха.
    """
    form_class = DeviceForm
    template_name = 'refbook/create_device.html'

    def post(self, request, *args, **kwargs):
        data = {}
        if request.is_ajax():
            form = self.get_form()
            if form.is_valid():
                form.save()
                data['status'] = 'ok'
                return JsonResponse(data)

            data['status'] = 'error'
            data['errors'] = form.errors
            return JsonResponse(data, status=400)

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

mysite/refbook/templates/refbook/create_device.html
{% extends 'base.html' %}
{% block title %} Создание девайса {% endblock %} 

{% block content %}

<div class="mt-5 text-center ">
    <a href="{% url 'refbook:device_list'%}">
        <button type="button" class="btn btn-primary col-lg-6 col-sm-10">
            На главную
        </button>
    </a>
</div>

<div class="row">
    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
        <form method="POST" novalidate>
            {% csrf_token %} {% for field in form %}

            <div class="form-group">
                {{ field.label_tag }} {{ field }} {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary saveButton">
                Сохранить
            </button>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("input").addClass("form-control");
        $("select").addClass("form-control");
        $("form").submit(function (e) {
            $(".form-error").remove();
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: '{% url "refbook:create_device" %}',
                data: $("form").serialize(),
                cache: true,
                success: function (data) {
                    if (data["status"] === "ok") {
                        alert("Девайс сохранён");
                    }
                    window.location.href = "{% url 'refbook:device_list' %}";
                },
                error: function (error) {
                    const data = error.responseJSON;
                    if (data["status"] === "error") {
                        Object.keys(data.errors).forEach(key => {
                            $(
                                `<p class="form-error form-text" style="color:#ff0000"><b>${data.errors[key]}</b></p>`
                            ).insertAfter(`#id_${key}`);
                        });
                        alert("Проверьте данные");
                    }
                }
            });
        });
    });
</script>
{% endblock %}

mysite/refbook/templates/refbook/list_devices.html
{% extends 'base.html' %}
{% block title %} Список девайсов {% endblock %}

{% block content %}
<div class="mt-5">
    <a href="{% url 'refbook:create_device'%}">
        <button type="button" class="btn btn-primary btn-block">
            Создать девайс
        </button>
    </a>
</div>

<div class="row mt-5 d-flex justify-content-around">
    {% for device in devices %}
    <div class="card mb-4" style="width: 30rem;">
        <div class="card-header">
            {{device.get_device_type_display}}
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Адрес размещения: {{device.address}}
            </li>
            <li class="list-group-item">
                Широта: {{device.latitude}}
            </li>
            <li class="list-group-item">
                Долгота: {{device.longitude}}
            </li>
            <li class="list-group-item">
                Радиус зоны звукопокрытия: {{device.sound_cover_zone}}
            </li>
        </ul>
    </div>
    {% endfor %}
</div>

{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#"><span>&laquo;</span></a>
        </li>
        {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i%}
        <li class="page-item active">
            <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>

        {% endif %} {% endfor %} {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#"><span>&raquo;</span></a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <main class="container">
        {% block content %}{% endblock %}
    </main>
</body>

</html>